version: '3'
services:
 terraform:
   container_name: terraform.local
   build: ./terraform_local
   image: terraform:latest
   tty: true
   volumes:
      - type: bind
        source: ./terraform
        target: /terraform
